USE [KOWA]
GO

DROP TABLE BILL_INPUT_DETAIL
/****** Object:  Table [dbo].[BILL_INPUT_DETAIL]    Script Date: 2019/05/24 13:27:08 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BILL_INPUT_DETAIL](
	[NO] [int] IDENTITY(1,1) NOT NULL,
	[BILL_NO] [int] NOT NULL,

	[CUST_NO] [nvarchar](20) NULL,
	[CUST_NAME] [nvarchar](50) NULL,

	[RESP_NUM] [int] NOT NULL,
	[LEFT_NUM] [int] NOT NULL,
	[RESP_DATE] [datetime] NULL,
	[PRICE] [int] NULL,
	[DISCOUNT_RATE] [numeric](8, 2) NULL,
	[REMARKS] [text] NULL,
	[CREATE_DATE] [datetime] NULL,
	[UPDATE_DATE] [datetime] NULL,
PRIMARY KEY CLUSTERED
(
	[NO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


